a panicking function std::process::abort is invoked: FAILURE
a panicking function std::process::abort is invoked: SUCCESS
