line 14 a panicking function std::process::abort is invoked: FAILURE
line 18 a panicking function std::process::abort is invoked: SUCCESS
